---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-server-2012r2
  # - name: windows-server-2016

suites:
  - name: default
    run_list:
      - recipe[provision::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
